### PR TITLE
Add recipe timings...

### PR DESCRIPTION
**Pull request by rathgar**
...and related schema micro-formats.

Screenshot 2020-02-25 at 15 07 32

The durations can be added to the front matter like so:
```yaml
---
layout: recipe
title:  Asparagus and Cheese Frittata
preptime: PT5M
cooktime: PT10M
---
```
The durations are entered in [ISO8601 Duration](https://en.wikipedia.org/wiki/ISO_8601#Durations) format. This is because we need it that way for the micro-format data and this way is far more preferable than trying to parse natural language. This format is actually pretty simple and easy to read. 

If preferred, we could drop the `PT` from the beginning eg: `cooktime: 1H30M`. It can be added back in automatically by the code. Anyone have an opinion? I'll make edits if this is preferred.

Right now this lets `activesupport/duration` do the heavy lifting of converting the duration into human readable strings. I have created a Jekyll filer `humanize_duration` to simplify the views. Because it's abstracted into a filter, the actual library doing the conversion can be changed at any time without affecting the rest of the code.

In order to load the dependency I've added a basic `Gemfile`. Those running jekyll via bundler will be grateful ;)

### CODE REVIEW

**Comment by clarklab** [comment]
Lookin good! A few thoughts:

- Time format: yeah I think I'd like to leave off the PT from the frontmatter. I know it's the official format, but entering just the time alone feels a bit smoother to me. To be clear, will the code accept lowercase values (example: 1h30m)?
- Does that dependency work with GitHub pages doing the build? Or places like Netlify? I've recently been eyeing my options for the main Chowdown site. Confession: I'm primarily a WordPress guy so I can probably use some help with the nuts and bolts of things like Jekyll and static hosting.

**Comment by rathgar** [comment]
I took at further look at the 'PT' thing as it slightly bugged the UX part of my brain. 

Case will be no problem, I already have a patch for that.

The 'P' is at the beginning of *all* durations and designates it as a Period, so that bit's easy. The `T` precedes the *time* part so as long as all recipes are shorter than one day, it's fine. However, if you're doing something like a sourdough starter (5-7 days) or century eggs (several months) you need to use the 'D' part:  `P7D` (7 days). 

Here's the ISO8601 designators:

- **P** duration designator ("period")
- **Y** years
- **M** month
- **W** week
- **D** days
- **T** precedes the time components
- **H** hours
- **M** minutes
- **S** seconds

My guess is the **T** designator was added to differentiate between **M**onths and **M**inutes. If we create our own format, we have to decide on that too. If someone puts `2m` is that two months or two minutes? It is a rare case but don't really want to inconvenience folk typing up recipes that take a long time. 

One idea would be to use uppercase for the most significant ([Y]ears, [M]onths, and [D]ays) and lowercase for the least significant ([h]ours, [m]inutes, and [s]econds). We'd then have entries such as:

- `1W` - one week
- `2h20m` - two hours, twenty minutes

It is highly unlikely that any recipe will combine both types (`1D12h` - 1 day, 12 hours) but it will cope fine. What do you think? I'm open to ideas.

I'll test using dependencies on my gh-pages and get back to you on that part.

**Comment by KN4CK3R** [comment]
Is it possible to translate the output? From the code (https://github.com/rails/rails/blob/master/activesupport/lib/active_support/duration.rb#L381) it looks like you can set a locale but does this work in Jekyll too?

**Comment by rathgar** [comment]
@KN4CK3R If you're using i18n support to handle translations for you then yes, not only very easy, but a lot of the time it's automatic. I saw you chose to roll your own - was there a rationale for that?

@clarklab I checked the GH docs and they recommend doing dependencies this way (via Gemfile) so you're safe to use them.

**Comment by KN4CK3R** [comment]
Lack of knowledge and an easy solution. If you know a plugin which can be used to support better translations and the duration output from your PR that would be great.

**Comment by rathgar** [comment]
@KN4CK3R No worries. I'd be happy to help out on that. I'll try and get something together that you and @clarklab can take a look at in a separate PR or branch. Might be a couple of weeks before I can but I'll do my best. It'll need to be fairly bulletproof and unintrusive. I'd be keen on it supporting multiple languages for seemless recipe translation as well.

**Comment by rathgar** [comment]
After some experimentation I've discovered that except those plugins/gems forcibly loaded by github, **all** plugins are clobbered. This means that processing in this method just won't work for github pages. This means we'd have to process ISO8601 in pure liquid which would be a massive pita if at all possible. It's a shame as this is nice to have.

I'll take a look at it at some point but for now I'll close this PR for tidiness.

**Comment by clarklab** [comment]
Continuing my role of "dude that knows jussst enough about Jekyll to be dangerous", would this Action be on any help to us? https://github.com/marketplace/actions/jekyll-action

It looks like it prebuilds on commit, but I'm worried it might make the repo confusing for beginners (me).

**Pull request closed without merging**
